### ISSUE TITLE
notebook | error linking extension

### ISSUE THREAD

**Issue by gasrios** [rossant/ipymd#94]
Hello! Is this project still being actively maintained? I'm running into the following error:

```
[W 2023-10-29 09:10:34.462 JupyterNotebookApp] 'contents_manager_class' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-10-29 09:10:34.863 ServerApp] notebook | error linking extension: The 'contents_manager_class' trait of <jupyter_server.serverapp.ServerApp object at 0x7f4ee1fff1c0> instance must be a type, but 'ipymd.IPymdContentsManager' could not be imported
    Traceback (most recent call last):
      File "/home/user/.local/lib/python3.10/site-packages/ipymd/core/contents_manager.py", line 28, in <module>
        from notebook.services.contents.filemanager import FileContentsManager
    ModuleNotFoundError: No module named 'notebook.services'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/user/.local/lib/python3.10/site-packages/traitlets/traitlets.py", line 2152, in validate
        value = self._resolve_string(value)
      File "/home/user/.local/lib/python3.10/site-packages/traitlets/traitlets.py", line 2028, in _resolve_string
        return import_item(string)
      File "/home/user/.local/lib/python3.10/site-packages/traitlets/utils/importstring.py", line 31, in import_item
        module = __import__(package, fromlist=[obj])
      File "/home/user/.local/lib/python3.10/site-packages/ipymd/__init__.py", line 3, in <module>
        from .core.contents_manager import IPymdContentsManager
      File "/home/user/.local/lib/python3.10/site-packages/ipymd/core/contents_manager.py", line 30, in <module>
        from IPython.html.services.contents.filemanager import FileContentsManager
    ModuleNotFoundError: No module named 'IPython.html'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/user/.local/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 342, in link_extension
        extension.link_all_points(self.serverapp)
      File "/home/user/.local/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 224, in link_all_points
        self.link_point(point_name, serverapp)
      File "/home/user/.local/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 214, in link_point
        point.link(serverapp)
      File "/home/user/.local/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 136, in link
        linker(serverapp)
      File "/home/user/.local/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 405, in _link_jupyter_server_extension
        self.serverapp.update_config(self.config)
      File "/home/user/.local/lib/python3.10/site-packages/traitlets/config/configurable.py", line 244, in update_config
        self._load_config(config)
      File "/home/user/.local/lib/python3.10/site-packages/traitlets/config/configurable.py", line 193, in _load_config
        setattr(self, name, deepcopy(config_value))
      File "/home/user/.local/lib/python3.10/site-packages/traitlets/traitlets.py", line 750, in __set__
        self.set(obj, value)
      File "/home/user/.local/lib/python3.10/site-packages/traitlets/traitlets.py", line 723, in set
        new_value = self._validate(obj, value)
      File "/home/user/.local/lib/python3.10/site-packages/traitlets/traitlets.py", line 756, in _validate
        value = self.validate(obj, value)
      File "/home/user/.local/lib/python3.10/site-packages/traitlets/traitlets.py", line 2154, in validate
        raise TraitError(
    traitlets.traitlets.TraitError: The 'contents_manager_class' trait of <jupyter_server.serverapp.ServerApp object at 0x7f4ee1fff1c0> instance must be a type, but 'ipymd.IPymdContentsManager' could not be imported
```
I'm glad to provide more information, in case there's interest in fixing it, though doing so on my own is beyond my Jupyter / Python knowledge.

Thanks!

**Comment by gasrios** [comment]
My mistake. According to https://pypi.org/project/notebook/, "The Jupyter Notebook project is currently undertaking a transition to a more modern code base built from the ground-up using JupyterLab components and extensions."

This applies to version 7 onwards. Forcing the installation of version 6 solved the problem.

I was aware ipymd does not work with JupyterLab, but not that Jupyter Notebook was using JupyterLab. Apologies
